---

- name: Setup facts with oracle java artifact
  set_fact:
    oracle_artifact: "{{ java_artifact_to_manage }}"
  when: java_artifact is defined

- name: Setup oracle java
  include_role:
    name: amtega.oracle_java
  vars:
    oracle_java_version: "{{ java_version }}"
    oracle_java_state: "{{ java_state }}"
    oracle_java_update_alternatives: "{{ java_update_alternatives }}"
    oracle_java_accept_license: yes
