---

- name: Setup openjdk
  include_role:
    name: amtega.openjdk
  vars:
    openjdk_version: "{{ java_version }}"
    openjdk_state: "{{ java_state }}"
    openjdk_update_alternatives: "{{ java_update_alternatives }}"
  when:
    - java_provider == "openjdk"

- name: Setup oracle java
  include_role:
    name: amtega.oracle_java
  vars:
    oracle_java_version: "{{ java_version }}"
    oracle_java_state: "{{ java_state }}"
    oracle_java_update_alternatives: "{{ java_update_alternatives }}"
    oracle_java_accept_license: yes
  when:
    - java_provider == "oracle"
